<?php
/**
 * @file
 * Pavel Ruban site main module.
 */

/**
 * Implements hook_init().
 */
function pavelruban_init() {
  $arg0 = arg(0);
//  if (!user_access('admin') && (!empty($arg0) && ($arg0 !== 'node' || $arg0 !== '<front>>'  || //$arg0 !== '/' || $arg0 !== 'user'))) {
//    drupal_not_found();
//  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function pavelruban_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' || $module == 'panels' || $module == 'page_manager' || $module == 'entityreference') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_ctools_plugin_api().
 */
function pavelruban_ctools_plugin_api($owner, $api) {
  if ($owner == 'panels') {
    return array('version' => 2.0);
  }
}

/**
 * Implements hook_entity_info_alter().
 */
function pavelruban_entity_info_alter(&$entity_info) {
  $view_modes = array(
    'user' => array(
      'comments',
    ),
  );

  foreach ($view_modes as $key => $entity_type) {
    foreach ($entity_type as $mode) {
      $entity_info[$key]['view modes'][$mode] = array(
        'label' => t(drupal_ucfirst(str_replace('_', ' ', $mode))),
        'custom settings' => TRUE,
      );
    }
  }
}
