<?php
/**
 * @file
 * Bean plugin for showing twitter feeds.
 */

/**
 * Implements hook_bean_types_api_info().
 */
function le_bean_bean_types_api_info() {
  return array('api' => 4);
}

/**
 * Implements hook_bean_types().
 */
function le_bean_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'le_bean') . '/plugins/bean';
  $plugins['le_twitter'] = array(
    'label' => t('Le360 twitter'),
    'handler' => array(
      'class' => 'LeTwitterBean',
      'parent' => 'bean',
      'path' => $plugin_path,
      'file' => 'le_bean.inc',
    ),
    'path' => $plugin_path,
    'file' => 'le_bean.inc',
  );
  return $plugins;
}
