<?php
/**
 * @file
 * Replace default node view counting by image pixel counter.
 */

define('PIXEL_NODE_VIEW_COUNTER_MODULE_PATH', drupal_get_path('module', 'pixel_node_view_counter'));

/**
 * Implements hook_page_alter().
 */
function pixel_node_view_counter_page_alter(&$page) {
  if (variable_get('pixel_node_view_counter_enabled', TRUE)) {
    $node = menu_get_object();
    if (arg(0) === 'node' && is_numeric(arg(1)) && (!arg(2) || arg(2) == 'view')) {
      $page['page_bottom']['pixel_node_view']['#markup'] = '<img style="position: fixed;" src="' . url(PIXEL_NODE_VIEW_COUNTER_MODULE_PATH . '/stat.php', array('query' => array('nid' => $node->nid))) . '" width="1" height="1" />';
    }
  }
}
