<?php
/**
 * @file
 * Provide functionallity of geopolis users module.
 */

/**
 * Implements hook_permission().
 */
function geopolis_users_permission() {

  $permissions = array(
    'access dashboard homepage',
    'access dashboard articles',
    'access dashboard blocs',
    'access dashboard pages',
    'access dashboard tags',
    'access dashboard reviews',
    'access dashboard assets',
    'access edit article_home nodequeue',
    'access edit article corps text format',
    'access edit article form blocs management ',
    'access toggle ckeditor text format',
  );

  $permissions_final = array();

  foreach ($permissions as $perm) {
    $permissions_final[$perm] = array(
      'title' => t($perm),
      'description' => t($perm),
      'restrict access' => TRUE,
    );
  }

  return $permissions_final;
}

/**
 * Return.
 */
function geopolis_users_get_pseudo_by_uid($uid) {
  $user = user_load($uid);
  return $user ? check_plain($user->field_user_nickname[LANGUAGE_NONE][0]['value']) : NULL;
}

/**
 * Fork nodequeue access callback.
 */
function geopolis_users_nodequeue_node_and_queue_access($node, $queue, $subqueue = NULL) {
  if ($queue->name == 'article_home') {
    if (!user_access('access edit article_home nodequeue')) {
      return FALSE;
    }
  }
  return nodequeue_nodequeue_access($node->type) && nodequeue_queue_access($queue, $subqueue);
}
