<?php

/**
 * @file
 * This module provides additional France Televisions specific features.
 *
 * @see http://disqus.com/
 */

/**
 * Implements hook_js_alter().
 *
 * Overrides Disqus javascript
 */
function ftv_disqus_js_alter(&$javascript) {
  // Replace disqus.js by ftv_disqus.js (wait for ajax callback before load disqus)
  if (isset($javascript[drupal_get_path('module', 'disqus') . '/disqus.js'])) {
    $javascript[drupal_get_path('module', 'disqus') . '/disqus.js']['data'] = drupal_get_path('module', 'ftv_disqus') . '/js/ftv_disqus.js';
  }
}

/**
 * Preprocess function for the ftv_janrain_capture_connection theming function.
 * We add javascript here instead of info file to make sure it is loaded only when it will be called.
 * @param $vars
 * @return void
 */
// function ftv_disqus_preprocess_ftv_janrain_capture_connection(&$vars) {
//   drupal_add_js(drupal_get_path('module', 'ftv_disqus') . '/js/ftv_disqus.js');
// }

/**
 * Implements hook_ftv_janrain_capture_user_alter().
 */
function ftv_disqus_ftv_janrain_capture_user_alter(&$commands = array()) {
  global $user;

  // Add all disqus configuration through ajax callback to allow page caching
  // for anonymous or authenticated users
  $disqus = '';

  // Check if we are to provide Single Sign-On access.
  if (variable_get('ftv_disqus_sso', FALSE)) {
    $data = array();

    // Inject the user data if it's available.
    if ($user->uid > 0) {
      $prefix_id = variable_get('ftv_disqus_sso_prefix_id_user', '9999');

      if (isset($_SESSION['janrain_capture_id']) && !empty($_SESSION['janrain_capture_id'])) {
        $data['id'] = $prefix_id . $_SESSION['janrain_capture_id'];
      }
      else {
        $data['id'] = $prefix_id . $user->uid;
      }

      $data['username'] = $user->name;
      $data['email'] = $user->mail;

      // Provide url of the avatar if available on Janrain
      if (isset($_SESSION['janrain_capture_photo']) && !empty($_SESSION['janrain_capture_photo'])) {
        $data['avatar'] = $_SESSION['janrain_capture_photo'];
      }
    }

    // Encode the data to be sent off to Disqus.
    $message = base64_encode(json_encode($data));
    $timestamp = time();
    $hmac = hash_hmac('sha1', "$message $timestamp", variable_get('disqus_secretkey', ''));

    // Stick the authentication requirements and data in the settings.
    $disqus['remote_auth_s3'] = "$message $hmac $timestamp";
    $disqus['api_key'] = variable_get('disqus_publickey', '');
  }

  // Execute Drupal.ajax.prototype.commands.check_missing_data
  $commands[] = array(
    'command' => 'ftv_disqus_user_config',
    'data' => array(
      'disqus_override_config' => $disqus,
    ),
  );
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function ftv_disqus_form_disqus_admin_settings_alter(&$form, &$form_state, $form_id) {

  $form['advanced']['ftv_disqus_sso'] = array(
    '#type' => 'checkbox',
    '#title' => t('FTV Single Sign-On'),
    '#description' => t('Provide FTV <a href="@sso">Single Sign-On</a> access to your site.', array(
      '@sso' => 'http://disqus.com/api/sso/',
    )),
    '#default_value' => variable_get('ftv_disqus_sso', FALSE),
    '#states' => array(
      'visible' => array(
        'input[name="disqus_publickey"]' => array('empty' => FALSE),
        'input[name="disqus_secretkey"]' => array('empty' => FALSE),
      ),
    ),
  );

  $form['advanced']['ftv_disqus_sso_prefix_id_user'] = array(
    '#type' => 'textfield',
    '#title' => t('Prefix for id user'),
    '#description' => t('By default, the id of the user will be janrain-[id-janrain] in Disqus SSO. You should change the prefix if you want to serapate and manage your own user in Disqus. Ex sport- or pluzz-'),
    '#default_value' => variable_get('ftv_disqus_sso_prefix_id_user', 'janrain-'),
    '#states' => array(
      'visible' => array(
        'input[name="disqus_publickey"]' => array('empty' => FALSE),
        'input[name="disqus_secretkey"]' => array('empty' => FALSE),
      ),
    ),
  );

  $form['#validate'][] = 'ftv_disqus_form_disqus_admin_settings_validate';
}


/**
 * Validate FTV Janrain Capture Form.
 *
 * We force that register form must be the same that signin form because
 * register with the signin form is possible with Janrain.
 */
function ftv_disqus_form_disqus_admin_settings_validate($form, &$form_state) {
  if ($form_state['values']['ftv_disqus_sso'] && ($form_state['values']['disqus_inherit_login'] || $form_state['values']['disqus_sso'] || $form_state['values']['disqus_localization'])) {
    form_set_error('disqus_sso', 'You need to disable Localization support + Inherit User Credentials + Disqus SSO if you use FTV Disqus SSO');
  }
}
