<?php
/**
 * @file
 * Code for the Sample Image gallery asset.
 */

/**
 * Implements hook_default_asset_type().
 */
function asset_gallery_default_asset_type() {
  $items = array();
  $items['gallery'] = entity_import('asset_type', '{
    "type" : "gallery",
    "name" : "Gallery",
    "icon" : "AddSlideshow.png",
    "description" : "",
    "help" : "",
    "weight" : "2",
    "locked" : "0",
    "rdf_mapping" : []
  }');
  return $items;
}

/**
 * Implements hook_views_api().
 */
function asset_gallery_views_api() {
  return array("version" => "3.0");
}

  /**
   * Implements hook_entity_info_alter().
   */
function asset_gallery_entity_info_alter(&$entity_info) {
  if (isset($entity_info['asset'])) {
    $entity_info['asset']['view modes']['gallery'] = array(
      'label' => t('Gallery'),
      'custom settings' => FALSE,
    );
  }
}

function asset_gallery_theme() {
  return array(
    'asset__image__gallery' => array(
      'template' => 'asset--image--gallery'
    ),
    'asset_wrapper__image__gallery' => array(
      'template' => 'asset-wrapper--image--gallery'
    ),
    'asset__gallery__full' => array(
      'template' => 'asset--gallery--full'
    ),
    'field__field_asset_image__image' => array(
      'template' => 'field--field-asset-image--image'
    ),
    'field__field_asset_gallery_images__gallery' => array(
      'template' => 'field--field-asset-gallery-images--gallery'
    )
  );
}

function asset_gallery_preprocess_entity(&$variables) {
  if ($variables['entity_type'] == 'asset') {
    $asset = $variables['asset'];
    if ($asset->type == 'image' && $variables['view_mode'] == 'gallery') {
      $content = $variables['content'];
      $item = $content['field_asset_image'][0];
      $caption = '';
      if (!empty($variables['field_asset_image_description'][0]['value'])) {
        $caption .= check_plain($variables['field_asset_image_description'][0]['value']);
      }
      if (!empty($variables['field_asset_image_copyright'][0]['value'])) {
        $caption .= '  © ' . check_plain($variables['field_asset_image_copyright'][0]['value']);
      }
      $variables['img_path'] = image_style_url($item['#image_style'], $item['#item']['uri']);
      $variables['caption'] = $caption;
    }
  }
}
